### PR TITLE
docs: add Ember Data transform page

### PR DESCRIPTION
**Pull request by SergeAstapov**
We started integrating TypeScript into existing application and stumbled upon custom transform.

https://docs.ember-cli-typescript.com/ember-data/models wasn't much helpful so I followed https://github.com/DefinitelyTyped/DefinitelyTyped/pull/50328/files and had to add interface to `TransformRegistry` to make TypeScript happy:

```typescript
declare module 'ember-data/types/registries/transform' {
  export default interface TransformRegistry {
    point: PointTransform;
  }
}
```

after that everything started to work as expected.

I know the prose is really bad but could not came up with anything better. Maybe we can collectively iterate over the prose if the snippets are good here.

### CODE REVIEW

**Comment by SergeAstapov** [comment]
Is this actually right/recommended way of extending `TransformRegistry`? Should we instead recommend to define these via `types/registries/transform.d.ts` like
```
export default interface TransformRegistry {
  point: PointTransform;
}
```

I'm new to ember-cli-typescript so would love to be guinea pig and test existing docs and identify what is missing

**Comment by chriskrycho** [comment]
Hi @SergeAstapov – thanks so much for this! I apologize I missed it when it came through; I need to tweak my notifications settings here. I'll try to review it on Friday!

**Comment by SergeAstapov** [comment]
Thank you @chriskrycho! I update PR to use more complex example with custom data structure. Please advice if this is not the canonical/suggested way of doing transforms, would love to hear back.

**Comment by chriskrycho** [comment]
@jamescdavis mind taking a look at this? You’re more up-to-date and well-informed on Ember Data than I am!

**Comment by chriskrycho** [comment]
I just went ahead and merged this; can iterate later! Thanks @SergeAstapov!

**Pull request merged**
