### PR TITLE
Update .npmignore to ignore .github and test folders

### PR DESCRIPTION
**Pull request by SergeAstapov**
This shrinks the "unpacked size" for a few Kb

Disclaimer: this is not necessarily an issue, just keep things clean.

Before the change `npm pack --dry-run` result

```
npm notice 
npm notice 📦  ember-cli-typescript@4.2.1
npm notice === Tarball Contents === 
npm notice 82B    .prettierignore                                                                  
npm notice 168B   commitlint.config.js                                                             
npm notice 90B    config/environment.js                                                            
npm notice 488B   index.js                                                                         
npm notice 718B   register-ts-node.js                                                              
npm notice 662B   .vscode/launch.json                                                              
npm notice 4.5kB  package.json                                                                     
npm notice 48B    renovate.json                                                                    
npm notice 444B   .vscode/settings.json                                                            
npm notice 696B   blueprint-files/ember-cli-typescript/tsconfig.json                               
npm notice 977B   tsconfig.json                                                                    
npm notice 2.0kB  .github/ISSUE_TEMPLATE/---build-bug.md                                           
npm notice 620B   .github/ISSUE_TEMPLATE/---build-enhancement.md                                   
npm notice 1.7kB  .github/ISSUE_TEMPLATE/---types-bug.md                                           
npm notice 1.2kB  .github/ISSUE_TEMPLATE/---types-enhancement.md                                   
npm notice 1.9kB  rfcs/0000-template.md                                                            
npm notice 37.1kB CHANGELOG.md                                                                     
npm notice 3.2kB  CODE_OF_CONDUCT.md                                                               
npm notice 9.2kB  docs/ember/components.md                                                         
npm notice 2.3kB  docs/legacy/computed-properties.md                                               
npm notice 3.9kB  docs/configuration.md                                                            
npm notice 7.8kB  docs/troubleshooting/conflicting-types.md                                        
npm notice 2.2kB  docs/ember/controllers.md                                                        
npm notice 2.5kB  docs/ts/current-limitations.md                                                   
npm notice 1.8kB  docs/ts/decorators.md                                                            
npm notice 18B    docs/legacy/ember-component.md                                                   
npm notice 5.6kB  docs/legacy/ember-object.md                                                      
npm notice 5.8kB  docs/ember/helpers.md                                                            
npm notice 1.7kB  docs/index.md                                                                    
npm notice 1.8kB  docs/installation.md                                                             
npm notice 1.7kB  .github/ISSUE_TEMPLATE.md                                                        
npm notice 1.2kB  known-typings.md                                                                 
npm notice 1.1kB  LICENSE.md                                                                       
npm notice 1.5kB  docs/legacy/mixins.md                                                            
npm notice 5.9kB  docs/ember-data/models.md                                                        
npm notice 1.1kB  docs/ts/package-names.md                                                         
npm notice 231B   .github/PULL_REQUEST_TEMPLATE.md                                                 
npm notice 469B   docs/cookbook/README.md                                                          
npm notice 420B   docs/ember-data/README.md                                                        
npm notice 566B   docs/ember/README.md                                                             
npm notice 720B   docs/legacy/README.md                                                            
npm notice 260B   docs/troubleshooting/README.md                                                   
npm notice 695B   docs/ts/README.md                                                                
npm notice 11.6kB README.md                                                                        
npm notice 6.9kB  rfcs/README.md                                                                   
npm notice 2.6kB  docs/ember/routes.md                                                             
npm notice 5.0kB  docs/ember/services.md                                                           
npm notice 1.3kB  docs/SUMMARY.md                                                                  
npm notice 12.8kB docs/ember/testing.md                                                            
npm notice 6.5kB  docs/upgrade-notes.md                                                            
npm notice 17.4kB docs/ts/using-ts-effectively.md                                                  
npm notice 5.6kB  docs/ts/with-addons.md                                                           
npm notice 2.2kB  docs/cookbook/working-with-route-models.md                                       
npm notice 57B    debug.sh                                                                         
npm notice 256B   is_md_only.sh                                                                    
npm notice 286B   blueprint-files/ember-cli-typescript/__config_root__/config/environment.d.ts     
npm notice 49B    blueprint-files/ember-cli-typescript/types/global.d.ts                           
npm notice 48B    blueprint-files/ember-cli-typescript/types/__app_name__/index.d.ts               
npm notice 102B   blueprint-files/ember-cli-typescript/types/ember-data/types/registries/model.d.ts
npm notice 46B    .gitbook.yaml                                                                    
npm notice 3.3kB  .github/workflows/ci.yml                                                         
npm notice === Tarball Details === 
npm notice name:          ember-cli-typescript                    
npm notice version:       4.2.1                                   
npm notice filename:      ember-cli-typescript-4.2.1.tgz          
npm notice package size:  62.5 kB                                 
npm notice unpacked size: 192.7 kB                                
npm notice shasum:        cf8386d00def58e2eeb62a2963032c0379900cbb
npm notice integrity:     sha512-skHJ+O2IFnrIF[...]CawNIAY4eunGA==
npm notice total files:   61                                      
npm notice 
ember-cli-typescript-4.2.1.tgz
```

After the change `npm pack --dry-run` result

```
npm notice 
npm notice 📦  ember-cli-typescript@4.2.1
npm notice === Tarball Contents === 
npm notice 1.4kB  .idea/ember-cli-typescript.iml                                                   
npm notice 90B    config/environment.js                                                            
npm notice 488B   index.js                                                                         
npm notice 718B   register-ts-node.js                                                              
npm notice 4.5kB  package.json                                                                     
npm notice 696B   blueprint-files/ember-cli-typescript/tsconfig.json                               
npm notice 977B   tsconfig.json                                                                    
npm notice 37.1kB CHANGELOG.md                                                                     
npm notice 9.2kB  docs/ember/components.md                                                         
npm notice 2.3kB  docs/legacy/computed-properties.md                                               
npm notice 3.9kB  docs/configuration.md                                                            
npm notice 7.8kB  docs/troubleshooting/conflicting-types.md                                        
npm notice 2.2kB  docs/ember/controllers.md                                                        
npm notice 2.5kB  docs/ts/current-limitations.md                                                   
npm notice 1.8kB  docs/ts/decorators.md                                                            
npm notice 18B    docs/legacy/ember-component.md                                                   
npm notice 5.6kB  docs/legacy/ember-object.md                                                      
npm notice 5.8kB  docs/ember/helpers.md                                                            
npm notice 1.7kB  docs/index.md                                                                    
npm notice 1.8kB  docs/installation.md                                                             
npm notice 1.2kB  known-typings.md                                                                 
npm notice 1.1kB  LICENSE.md                                                                       
npm notice 1.5kB  docs/legacy/mixins.md                                                            
npm notice 5.9kB  docs/ember-data/models.md                                                        
npm notice 1.1kB  docs/ts/package-names.md                                                         
npm notice 469B   docs/cookbook/README.md                                                          
npm notice 420B   docs/ember-data/README.md                                                        
npm notice 566B   docs/ember/README.md                                                             
npm notice 720B   docs/legacy/README.md                                                            
npm notice 260B   docs/troubleshooting/README.md                                                   
npm notice 695B   docs/ts/README.md                                                                
npm notice 11.6kB README.md                                                                        
npm notice 2.6kB  docs/ember/routes.md                                                             
npm notice 5.0kB  docs/ember/services.md                                                           
npm notice 1.3kB  docs/SUMMARY.md                                                                  
npm notice 12.8kB docs/ember/testing.md                                                            
npm notice 6.5kB  docs/upgrade-notes.md                                                            
npm notice 17.4kB docs/ts/using-ts-effectively.md                                                  
npm notice 5.6kB  docs/ts/with-addons.md                                                           
npm notice 2.2kB  docs/cookbook/working-with-route-models.md                                       
npm notice 286B   blueprint-files/ember-cli-typescript/__config_root__/config/environment.d.ts     
npm notice 49B    blueprint-files/ember-cli-typescript/types/global.d.ts                           
npm notice 48B    blueprint-files/ember-cli-typescript/types/__app_name__/index.d.ts               
npm notice 102B   blueprint-files/ember-cli-typescript/types/ember-data/types/registries/model.d.ts
npm notice 142B   .idea/codeStyles/codeStyleConfig.xml                                             
npm notice 568B   .idea/jsLinters/jshint.xml                                                       
npm notice 292B   .idea/modules.xml                                                                
npm notice 345B   .idea/inspectionProfiles/Project_Default.xml                                     
npm notice 2.9kB  .idea/codeStyles/Project.xml                                                     
npm notice 180B   .idea/vcs.xml                                                                    
npm notice === Tarball Details === 
npm notice name:          ember-cli-typescript                    
npm notice version:       4.2.1                                   
npm notice filename:      ember-cli-typescript-4.2.1.tgz          
npm notice package size:  55.2 kB                                 
npm notice unpacked size: 173.9 kB                                
npm notice shasum:        7417cd8ce7e0b17f7ad6e5cfb87c3d731a767891
npm notice integrity:     sha512-DPilyQT2BYWLV[...]vFnRbNuFd6tzw==
npm notice total files:   50                                      
npm notice 
ember-cli-typescript-4.2.1.tgz
```

### CODE REVIEW

**Comment by SergeAstapov** [comment]
I wonder if we can skip `docs` folder from publishing as in that case we'll have

```
npm notice === Tarball Details === 
npm notice name:          ember-cli-typescript                    
npm notice version:       4.2.1                                   
npm notice filename:      ember-cli-typescript-4.2.1.tgz          
npm notice package size:  19.4 kB                                 
npm notice unpacked size: 64.7 kB                                 
npm notice shasum:        a7fc0543c7f5fd53463ba903370aef895bbda036
npm notice integrity:     sha512-oJcMS/EaXu4oF[...]eh4R3PUMY6ZVA==
npm notice total files:   21                                      
npm notice 
ember-cli-typescript-4.2.1.tgz
```

**Comment by chriskrycho** [comment]
With apologies, can you rebase? I just re-enabled CI (which had, annoyingly, gotten automatically turned off).

**Comment by SergeAstapov** [comment]
@chriskrycho rebased!

>  1 workflow awaiting approval
> First-time contributors need a maintainer to approve running workflows.

@chriskrycho mind to approve the PR to kick off CI?

**Comment by SergeAstapov** [comment]
@chriskrycho I assume CI failures unrelated (at least ember-cli latest/beta scenarios fail because of Node.js 12 compatibility)

**Comment by chriskrycho** [comment]
CI issues seem to be unrelated; will get them resolved independently. Thanks!

**Pull request merged**
