### PR TITLE
feat: add ember-data packages types if supported

### LINKED ISSUE #1109: Install @types/ember-data__* by default
This is a reminder issue, for https://discordapp.com/channels/480462759797063690/484421406659182603/683369672594292750

at the moment, `@ember-data/` types are not installed

### PR DESCRIPTION
**Pull request by makepanic**
feat(blueprint): add ember-data packages types if supported

fixes #1109

### CODE REVIEW

**Comment by makepanic** [comment]
Seems like somehow VersionChecker isn't getting the dependencies in the ember-cli-blueprint-test-helpers context :thinking:

**Comment by chriskrycho** [comment]
Oh snap, I didn't realize this was open! Adding it to my queue to make sure we get it knocked out this week. @makepanic can you do a rebase?

**Comment by chriskrycho** [comment]
@makepanic feel like rebasing and landing? If I don't hear from you in a day or two, I'll try to pick it up and rebase myself. (No worries!)

**Comment by MrChocolatine** [comment]
I think we could move forward with this pull request.

I am trying to work on this but I am facing the same error as the [author mentioned above](https://github.com/typed-ember/ember-cli-typescript/pull/1142#issuecomment-611167728):
> Seems like somehow VersionChecker isn't getting the dependencies in the ember-cli-blueprint-test-helpers context 🤔

I left a comment on `ember-cli-version-checker`:
https://github.com/ember-cli/ember-cli-version-checker/issues/22#issuecomment-778788058

**Comment by jamescdavis** [comment]
Fixed in #1411

**Pull request closed without merging**
