### PR TITLE
`ember-test-helpers` -> `@ember/test-helpers`

### PR DESCRIPTION
**Pull request by charlesfries**

### CODE REVIEW

**Review by chriskrycho — APPROVED** [review]
Thank you!

**Comment by chriskrycho** [comment]
Mind a rebase?

**Comment by charlesfries** [comment]
Somehow I always end up bungling these rebases 🤦 Anyways it looks like all of my changes are already in master. Closing

**Comment by chriskrycho** [comment]
Thank you again!

**Pull request closed without merging**
