### PR TITLE
docs: Update README.md

### PR DESCRIPTION
**Pull request by vitch**
Fix link to "packages this addon installs"

### CODE REVIEW

**Review by chriskrycho — APPROVED** [review]
Thank you so much for this!

**Comment by vitch** [comment]
Failed linting because I authored it in the GitHub UI and didn't think about commitlint. I'll fix...

**Comment by vitch** [comment]
Hopefully that helps?

**Comment by chriskrycho** [comment]
Sorry for the delay on this, @vitch – been busy. I actually just updated our setup not to put that burden on contributors; we'll take care of it as maintainers from now on. This should pass CI shortly and I'll merge it!

**Pull request merged**
