### PR TITLE
Azure Pipelines: XUnit Test Report

### PR DESCRIPTION
**Pull request by mike-north**

### CODE REVIEW

**Comment by mike-north** [comment]
Azure doesn't seem to be happy with the XML files. Cutting my losses for now

**Comment by PBoraMSFT** [comment]
@mike-north - I am a Program Manager on the Azure Pipelines team. We are looking into this issue and will get back.

**Comment by mike-north** [comment]
@SadagopanRajaram If you checkout this branch you can run the same command that's in the CI config.

```
mocha --recursive js/tests -R xunit > node-tests.xml
```

###### node-tests.xml
```xml
<testsuite name="Mocha Tests" tests="16" failures="0" errors="0" skipped="0" timestamp="Wed, 31 Oct 2018 01:21:47 GMT" time="29.131">
	<testcase classname="Acceptance: build" name="builds and rebuilds files" time="4.483"/>
	<testcase classname="Acceptance: build" name="fails the build when noEmitOnError is set and an error is emitted" time="3.652"/>
	<testcase classname="Acceptance: ember-cli-typescript generator" name="basic app" time="1.529"/>
	<testcase classname="Acceptance: ember-cli-typescript generator" name="basic addon" time="0.576"/>
	<testcase classname="Acceptance: ember-cli-typescript generator" name="in-repo addons" time="0.586"/>
	<testcase classname="Acceptance: ember-cli-typescript generator" name="app with Mirage" time="0.549"/>
	<testcase classname="Acceptance: ember-cli-typescript generator" name="addon with Mirage" time="0.562"/>
	<testcase classname="Acceptance: ember-cli-typescript generator" name="app with Mocha" time="0.563"/>
	<testcase classname="Acceptance: ember-cli-typescript generator" name="addon with Mocha" time="0.558"/>
	<testcase classname="Acceptance: ember-cli-typescript generator module unification" name="basic app" time="0.629"/>
	<testcase classname="Acceptance: ember-cli-typescript generator module unification" name="basic addon" time="0.68"/>
	<testcase classname="Acceptance: TypeScript blueprints" name="uses blueprints from ember-cli-typescript-blueprints" time="1.196"/>
	<testcase classname="Acceptance: ts:clean command" name="removes all generated files" time="2.969"/>
	<testcase classname="Acceptance: ts:precompile command" name="generates .js and .d.ts files from the addon tree" time="2.941"/>
	<testcase classname="Acceptance: ts:precompile command" name="generates .js files only from the app tree" time="2.536"/>
	<testcase classname="Acceptance: ts:precompile command module unification" name="generates .js and .d.ts files from the src tree" time="2.637"/>
</testsuite>
```

**Comment by jamescdavis** [comment]
The other thing here is I don't think `ember test -r xunit > ember-tests.xml` will not yield a clean xml file. I think what we need to do is to specify a report file in the testem config. We can also set `xunit_intermediate_output: true` to get it to continue to output TAP to stdout for Travis build log (and Azure) while dumping xunit to file. Something like this in testem.js should do:
```js
module.exports = {
  reporter: 'xunit',
  report_file: 'ember-tests.xml',
  xunit_exclude_stack: true, // we *probably* want this on to keep the xunit file clean
  xunit_intermediate_output: true,
};

**Comment by mike-north** [comment]
Good suggestion @jamescdavis 

##### ember-test.xml
```xml
<testsuite name="Testem Tests" tests="24" skipped="0" failures="0" timestamp="Fri Nov 02 2018 10:38:22 GMT-0700 (Pacific Daylight Time)" time="1.643">
  <testcase classname="Chrome 70.0" name="ESLint | app: app/shadowed-file.js" time="0.003"/>
  <testcase classname="Chrome 70.0" name="Integration | Component | js importing ts: it renders" time="0.277"/>
  <testcase classname="Chrome 70.0" name="Integration | Component | ts component: it renders" time="0.093"/>
  <testcase classname="Chrome 70.0" name="ESLint | app: app.js" time="0"/>
  <testcase classname="Chrome 70.0" name="ESLint | app: components/js-importing-ts.js" time="0.001"/>
  <testcase classname="Chrome 70.0" name="ESLint | app: components/test-one.js" time="0"/>
  <testcase classname="Chrome 70.0" name="ESLint | app: helpers/js-help.js" time="0"/>
  <testcase classname="Chrome 70.0" name="ESLint | app: resolver.js" time="0"/>
  <testcase classname="Chrome 70.0" name="ESLint | app: router.js" time="0.001"/>
  <testcase classname="Chrome 70.0" name="ESLint | tests: integration/components/js-importing-ts-test.js" time="0"/>
  <testcase classname="Chrome 70.0" name="ESLint | tests: integration/components/ts-component-test.js" time="0"/>
  <testcase classname="Chrome 70.0" name="ESLint | tests: test-helper.js" time="0"/>
  <testcase classname="Chrome 70.0" name="ESLint | tests: unit/helpers/js-help-test.js" time="0"/>
  <testcase classname="Chrome 70.0" name="ESLint | tests: unit/helpers/typed-help-test.js" time="0"/>
  <testcase classname="Chrome 70.0" name="Unit | Build: in-repo addons' addon trees wind up in the right place" time="0"/>
  <testcase classname="Chrome 70.0" name="Unit | Build: in-repo addons' app trees wind up in the right place" time="0"/>
  <testcase classname="Chrome 70.0" name="Unit | Build: app files aren't shadowed by addons' app tree files" time="0.001"/>
  <testcase classname="Chrome 70.0" name="Unit | Build: MU app files wind up in the right place" time="0"/>
  <testcase classname="Chrome 70.0" name="Unit | Build: MU addon files wind up in the right place" time="0"/>
  <testcase classname="Chrome 70.0" name="Unit | Build: addon's addon-test-support files end up in &lt;addon-name>/test-support/*" time="0"/>
  <testcase classname="Chrome 70.0" name="Unit | Build: addon's test-support files end up in dummy/tests/*" time="0"/>
  <testcase classname="Chrome 70.0" name="Unit | Helper | js help: it works" time="0"/>
  <testcase classname="Chrome 70.0" name="Unit | Helper | typed help: it works" time="0.001"/>
  <testcase classname="Chrome 70.0" name="ember-qunit: Ember.onerror validation: Ember.onerror is functioning properly" time="0"/>
</testsuite>
```

**Comment by PBoraMSFT** [comment]
@SadagopanRajaram - good to see this is now working. Thanks for the quick follow through.

@mike-north - please do let us know if you run into any other issues.

**Pull request merged**
