### PR TITLE
Ignore node_modules hoisted above project root

### PR DESCRIPTION
**Pull request by allenylzhou**
For an ember project set up with yarn workspaces (https://yarnpkg.com/lang/en/docs/workspaces/), running `ember s` can cause the process to potentially hang due to DirectoryWatcher firing in a loop on the tmp folder.

Steps to reproduce:
1. `git clone https://github.com/allenylzhou/yarn-workspaces-ember-engine`
2. `cd yarn-workspaces-ember-engine`
3. `yarn install`
4. `cd packages/my-new-engine`
5. `DEBUG=ember-cli-typescript* ember s`

```
ember-cli-typescript:compiler-state tscDidStart | broccoli: 0 active nodes | tsc: building (0 errors) +7ms
  ember-cli-typescript:tsc:trace DirectoryWatcher:: Triggered with /Users/allenylzhou/Sandbox/yarn-workspaces-ember-engine/node_modules/my-new-engine/tmp/broccoli_persistent_filtereslint_validation_filter-output_path-2sThMjmK.tmp/unit/.gitkeep:: WatchInfo: /Users/allenylzhou/Sandbox/yarn-workspaces-ember-engine/node_modules 1 Failed Lookup Locations +0ms
  ember-cli-typescript:tsc:trace Elapsed:: 0ms DirectoryWatcher:: Triggered with /Users/allenylzhou/Sandbox/yarn-workspaces-ember-engine/node_modules/my-new-engine/tmp/broccoli_persistent_filtereslint_validation_filter-output_path-2sThMjmK.tmp/unit/.gitkeep:: WatchInfo: /Users/allenylzhou/Sandbox/yarn-workspaces-ember-engine/node_modules 1 Failed Lookup Locations +0ms
  ember-cli-typescript:tsc:trace DirectoryWatcher:: Triggered with /Users/allenylzhou/Sandbox/yarn-workspaces-ember-engine/node_modules/my-new-engine/tmp/funnel-output_path-wkFpdo95.tmp/dummy/tests:: WatchInfo: /Users/allenylzhou/Sandbox/yarn-workspaces-ember-engine/node_modules 1 Failed Lookup Locations +0ms
  ember-cli-typescript:tsc:trace Elapsed:: 0ms DirectoryWatcher:: Triggered with /Users/allenylzhou/Sandbox/yarn-workspaces-ember-engine/node_modules/my-new-engine/tmp/funnel-output_path-wkFpdo95.tmp/dummy/tests:: WatchInfo: /Users/allenylzhou/Sandbox/yarn-workspaces-ember-engine/node_modules 1 Failed Lookup Locations +0ms
  ember-cli-typescript:tsc:trace DirectoryWatcher:: Triggered with /Users/allenylzhou/Sandbox/yarn-workspaces-ember-engine/node_modules/my-new-engine/tmp/config_replace-input_base_path-RXiRuroO.tmp/0/amd-shim.js:: WatchInfo: /Users/allenylzhou/Sandbox/yarn-workspaces-ember-engine/node_modules 1 Failed Lookup Locations +41ms
  ember-cli-typescript:tsc:trace Elapsed:: 2ms DirectoryWatcher:: Triggered with /Users/allenylzhou/Sandbox/yarn-workspaces-ember-engine/node_modules/my-new-engine/tmp/config_replace-input_base_path-RXiRuroO.tmp/0/amd-shim.js:: WatchInfo: /Users/allenylzhou/Sandbox/yarn-workspaces-ember-engine/node_modules 1 Failed Lookup Locations +2ms
  ember-cli-typescript:tsc:trace DirectoryWatcher:: Triggered with /Users/allenylzhou/Sandbox/yarn-workspaces-ember-engine/node_modules/my-new-engine/tmp/config_replace-input_base_path-RXiRuroO.tmp/0/app-boot.js:: WatchInfo: /Users/allenylzhou/Sandbox/yarn-workspaces-ember-engine/node_modules 1 Failed Lookup Locations +0ms
  ember-cli-typescript:tsc:trace Elapsed:: 2ms DirectoryWatcher:: Triggered with /Users/allenylzhou/Sandbox/yarn-workspaces-ember-engine/node_modules/my-new-engine/tmp/config_replace-input_base_path-RXiRuroO.tmp/0/app-boot.js:: WatchInfo: /Users/allenylzhou/Sandbox/yarn-workspaces-ember-engine/node_modules 1 Failed Lookup Locations +3ms
  ember-cli-typescript:tsc:trace DirectoryWatcher:: Triggered with /Users/allenylzhou/Sandbox/yarn-workspaces-ember-engine/node_modules/my-new-engine/tmp/config_replace-input_base_path-RXiRuroO.tmp/0/app-config-from-meta.js:: WatchInfo: /Users/allenylzhou/Sandbox/yarn-workspaces-ember-engine/node_modules 1 Failed Lookup Locations +0ms
  ember-cli-typescript:tsc:trace Elapsed:: 3ms DirectoryWatcher:: Triggered with /Users/allenylzhou/Sandbox/yarn-workspaces-ember-engine/node_modules/my-new-engine/tmp/config_replace-input_base_path-RXiRuroO.tmp/0/app-config-from-meta.js:: WatchInfo: /Users/allenylzhou/Sandbox/yarn-workspaces-ember-engine/node_modules 1 Failed Lookup Locations +3ms
  ember-cli-typescript:tsc:trace DirectoryWatcher:: Triggered with /Users/allenylzhou/Sandbox/yarn-workspaces-ember-engine/node_modules/my-new-engine/tmp/config_replace-input_base_path-RXiRuroO.tmp/0/app-config.js:: WatchInfo: /Users/allenylzhou/Sandbox/yarn-workspaces-ember-engine/node_modules 1 Failed Lookup Locations +0ms
  ember-cli-typescript:tsc:trace Elapsed:: 2ms DirectoryWatcher:: Triggered with /Users/allenylzhou/Sandbox/yarn-workspaces-ember-engine/node_modules/my-new-engine/tmp/config_replace-input_base_path-RXiRuroO.tmp/0/app-config.js:: WatchInfo: /Users/allenylzhou/Sandbox/yarn-workspaces-ember-engine/node_modules 1 Failed Lookup Locations +2ms
  ember-cli-typescript:tsc:trace DirectoryWatcher:: Triggered with /Users/allenylzhou/Sandbox/yarn-workspaces-ember-engine/node_modules/my-new-engine/tmp/config_replace-input_base_path-RXiRuroO.tmp/0/app-prefix.js:: WatchInfo: /Users/allenylzhou/Sandbox/yarn-workspaces-ember-engine/node_modules 1 Failed Lookup Locations +0ms
  ember-cli-typescript:tsc:trace Elapsed:: 4ms DirectoryWatcher:: Triggered with /Users/allenylzhou/Sandbox/yarn-workspaces-ember-engine/node_modules/my-new-engine/tmp/config_replace-input_base_path-RXiRuroO.tmp/0/app-prefix.js:: WatchInfo: /Users/allenylzhou/Sandbox/yarn-workspaces-ember-engine/node_modules 1 Failed Lookup Locations +4ms
  ember-cli-typescript:tsc:trace DirectoryWatcher:: Triggered with /Users/allenylzhou/Sandbox/yarn-workspaces-ember-engine/node_modules/my-new-engine/tmp/config_replace-input_base_path-RXiRuroO.tmp/0/app-suffix.js:: WatchInfo: /Users/allenylzhou/Sandbox/yarn-workspaces-ember-engine/node_modules 1 Failed Lookup Locations +0ms
  ember-cli-typescript:tsc:trace Elapsed:: 2ms DirectoryWatcher:: Triggered with /Users/allenylzhou/Sandbox/yarn-workspaces-ember-engine/node_modules/my-new-engine/tmp/config_replace-input_base_path-RXiRuroO.tmp/0/app-suffix.js:: WatchInfo: /Users/allenylzhou/Sandbox/yarn-workspaces-ember-engine/node_modules 1 Failed Lookup Locations +2ms
  ember-cli-typescript:tsc:trace DirectoryWatcher:: Triggered with /Users/allenylzhou/Sandbox/yarn-workspaces-ember-engine/node_modules/my-new-engine/tmp/config_replace-input_base_path-RXiRuroO.tmp/0/assembler.js:: WatchInfo: /Users/allenylzhou/Sandbox/yarn-workspaces-ember-engine/node_modules 1 Failed Lookup Locations +0ms
  ember-cli-typescript:tsc:trace Elapsed:: 4ms DirectoryWatcher:: Triggered with /Users/allenylzhou/Sandbox/yarn-workspaces-ember-engine/node_modules/my-new-engine/tmp/config_replace-input_base_path-RXiRuroO.tmp/0/assembler.js:: WatchInfo: /Users/allenylzhou/Sandbox/yarn-workspaces-ember-engine/node_modules 1 Failed Lookup Locations +4ms
  ember-cli-typescript:tsc:trace DirectoryWatcher:: Triggered with /Users/allenylzhou/Sandbox/yarn-workspaces-ember-engine/node_modules/my-new-engine/tmp/config_replace-input_base_path-RXiRuroO.tmp/0/babel-process-modules-only.js:: WatchInfo: /Users/allenylzhou/Sandbox/yarn-workspaces-ember-engine/node_modules 1 Failed Lookup Locations +1ms
  ember-cli-typescript:tsc:trace Elapsed:: 2ms DirectoryWatcher:: Triggered with /Users/allenylzhou/Sandbox/yarn-workspaces-ember-engine/node_modules/my-new-engine/tmp/config_replace-input_base_path-RXiRuroO.tmp/0/babel-process-modules-only.js:: WatchInfo: /Users/allenylzhou/Sandbox/yarn-workspaces-ember-engine/node_modules 1 Failed Lookup Locations +2ms
```

The reason is because yarn workspaces hoists node_modules into an ancestor dir of `project.root` (which is `/Users/allenylzhou/Sandbox/yarn-workspaces-ember-engine/packages/my-new-engine` instead of `/Users/allenylzhou/Sandbox/yarn-workspaces-ember-engine`) Inside this top level node_modules folder are symlinks to the projects in the yarn workspace which contain tmp. Since the top level node_modules are not being ignored by the watcher, the tmp folders  also end up being watched.

I added a glob pattern to chokidar ignored to fix this.

### CODE REVIEW

**Comment by chriskrycho** [comment]
Thanks for this PR, @allenylzhou, and sorry for the delay in responding to it! Someone will test it out and get it merged soonish!

**Comment by gossi** [comment]
I tried this PR as @chriskrycho pointed this to me for #234. I got checky and tried two different versions of `package.json` for the workspace/root folder:

1) Regular `packages/*`:

```json
{
	"private": true,
	"devDependencies": {
		"lerna": "^2.11.0"
	},
	"workspaces": [
		"packages/*"
	]
}
```

✅  works

2) No sub-folder `*`:

```json
{
	"private": true,
	"devDependencies": {
		"lerna": "^2.11.0"
	},
	"workspaces": [
		"*"
	]
}
```

⛔️ Dang! Stops for the same reason as the original problem.

**Comment by makepanic** [comment]
Just to confirm, this PR makes yarn workspaces (using hardcoded `workspaces`) work for us.

Thanks

**Comment by chriskrycho** [comment]
Thanks for the reports, @makepanic and @gossi! Now we need to get this branch updated with *other* changes we landed in the same space – @allenylzhou can you merge `master` in here and get the changes integrated? Then we'll confirm *again* that it works with everyone and then get it merged.

**Comment by allenylzhou** [comment]
@chriskrycho I rebased my changes on top of master.

@gossi I cannot reproduce case `2. No sub folder *`. Do you have a barebones project set up for me to test out?

**Comment by gossi** [comment]
I retested this. This time it worked, yeah! I maybe had some old clunky stuff in my folder the last time, so it wasn't really clean to run this test. Doesn't matter since it worked.

@chriskrycho guess this is ready to merge then?

**Comment by chriskrycho** [comment]
Huzzah! I'll also test it and then merge it!

**Comment by dfreeman** [comment]
The one reservation I have about this change is that I believe it will cause changes in linked developing addons not to be picked up, since their relative path involves `node_modules` — that's the reason we anchored our `ignore` array at the project root in the first place.

We may need to rethink our strategy for doing development in a host app with TypeScript addons anyway, as it's fairly cumbersome in cases where the host isn't using TS itself.

**Pull request merged**
