### PR TITLE
Restrict `@babel/plugin-transform-typescript` to v7.4.x

### PR DESCRIPTION
**Pull request by Turbo87**
see https://github.com/babel/babel/issues/10162

### CODE REVIEW

**Comment by makepanic** [comment]
you could probably change the commit message to:

```
build: restrict `@babel/plugin-transform-typescript` to v7.4.x

see babel/babel#10162
```

to make it less pointless

**Comment by Turbo87** [comment]
I can't, it won't even let me amend the commit in my Git UI...

**Comment by dfreeman** [comment]
Thanks @Turbo87 — `v2.0.2` is out with this fix, and the corresponding forward-port to master is in #752.

**Comment by Turbo87** [comment]
@dfreeman perfect, thanks! 🙏

**Pull request closed without merging**
