### PR TITLE
enable `allowSyntheticDefaultImports` in tsconfig

### PR DESCRIPTION
**Pull request by dwickern**
This will make these imports work
```ts
import $ from 'jquery';
import RSVP from 'rsvp';
```

Since those typings use `export =` instead of `export default`

### CODE REVIEW

**Comment by chriskrycho** [comment]
That's what I tried earlier, but no dice. 😖

**Comment by dwickern** [comment]
The error now is 
> node_modules/@types/ember/index.d.ts(13,8): error TS1192: Module '"/home/travis/build/typed-ember/ember-cli-typescript/node_modules/@types/rsvp/index"' has no default export.

So I think we need to update the ember typings also (or pin `@types/rsvp` to an older version for now)

**Comment by chriskrycho** [comment]
Ah, I see. Let's pin to the earlier version for now.

**Comment by chriskrycho** [comment]
Here's a question I don't know the answer to: how do DT types work with real package dependencies? My goal is to upstream RSVP types to RSVP itself by the end of the week. I have no idea, though, what the answer is to this question.

**Comment by dwickern** [comment]
They let you add a `package.json` with a `"dependencies"` (and nothing else). I think that's why

https://github.com/DefinitelyTyped/DefinitelyTyped#i-notice-some-packages-having-a-packagejson-here

**Comment by dwickern** [comment]
You would also need to update the notNeededPackages on DT for RSVP

**Comment by chriskrycho** [comment]
👍 excellent; thank you. I'd poked around at that question before but never found my way to that answer. I'll get that rolling probably Thursday.

**Comment by chriskrycho** [comment]
I *think* this is now defunct, b/c we have RSVP@4.0.0+ in DT and that's _not_ using synthetic exports?

**Comment by chriskrycho** [comment]
Same as other recently merged branches: Travis failure is spurious.

**Pull request merged**
