### PR TITLE
De-simplify watcher

### LINKED ISSUE #204: tsc ignoring file change & hanging build when watching
`tsc` is ignoring a `.ts` file change, and because of that, ember-cli is hanging the build.

- typescript v2.8.3
- ember-cli-typescript v1.3.0"
- node.js  v8.11.1
- ember-cli v3.2.1

```
⚡ ember build -w

Build successful (19446ms)

Slowest Nodes (totalTime => 5% )              | Total (avg)         
----------------------------------------------+---------------------
Babel (47)                                    | 8687ms (184 ms)     
EslintValidationFilter (7)                    | 3716ms (530 ms)     
Concat (13)                                   | 2497ms (192 ms)     

file changed controllers/login.ts
file changed controllers/login.ts
```

Could not reproduce using the dummy app in ember-cli-typescript.
I tried using the default install of the tsconfig.json proivided by ember-cli-typescript.
I also tried adding ember-decorators to the dummy app as our app uses decorators.

Not sure what the issue is with our app setup. We use in-repro addons, and a bunch of dependencies. The apps have mostly .js still as we are moving toward more TS use. Changes to .js files work fine.

Using `DEBUG=\* ember b -w` ....

```
  ember-cli-typescript:tsc:trace DirectoryWatcher:: Triggered with /pathtoapp/app/controllers/login.ts:: WatchInfo: /pathtoapp 1 +55s
  ember-cli-typescript:tsc:trace Elapsed:: 102ms DirectoryWatcher:: Triggered with /pathtoapp/app/controllers/login.ts:: WatchInfo: /pathtoapp 1 +102ms
  ember-cli-typescript:compiler-state tscDidStart | broccoli: 0 active nodes | tsc: building (0 errors) +33s
  ember-cli-typescript:tsc:trace DirectoryWatcher:: Triggered with /pathtoapp/app/controllers/login.ts:: WatchInfo: /pathtoapp 1 +2ms
  ember-cli-typescript:tsc:trace Elapsed:: 57ms DirectoryWatcher:: Triggered with /pathtoapp/app/controllers/login.ts:: WatchInfo: /pathtoapp 1 +57ms
  ember-cli-typescript:compiler-state tscDidStart | broccoli: 0 active nodes | tsc: building (0 errors) +59ms
file changed controllers/login.ts
  broccoli-sane-watcher scheduleBuild: /pathtoapp/app/controllers/login.ts +30s
file changed controllers/login.ts
  broccoli-sane-watcher debounce scheduleBuild: /pathtoapp/app/controllers/login.ts +1ms
  broccoli-sane-watcher build: /pathtoapp/app/controllers/login.ts +100ms
  broccoli-sane-watcher { type: 'rebuild', reason: 'watcher', primaryFile: '/pathtoapp/app/controllers/login.ts', changedFiles: [ '/pathtoapp/app/controllers/login.ts', '/pathtoapp/app/controllers/login.ts' ] } +0ms
 ...

  async-promise-queue: started, with concurrency=1 +0ms
  broccoli-persistent-filter:Babel > [Babel: ember-cli-app-version] [TreeMerger (addon)#4153 -> broccoli-persistent-filter:Babel > [Babel: ember-cli-app-version]: Babel: ember-cli-app-version#4213 -> applyPatches#4220] applyPatches duration: 0.13 ms {"mkdir":0,"rmdir":0,"unlink":0,"change":0,"create":0,"other":0,"processed":0,"linked":0,"processString":0,"processStringTime":0,"persistentCacheHit":0,"persistentCachePrime":0} +0ms
  ember-cli-typescript:compiler-state broccoliDidStart | broccoli: 1 active nodes | tsc: building (0 errors) +172ms
```

The work around for us is to use : `ember install ember-cli-typescript@v1.3.0-beta.4`

I'll try to post a repo once I can make one without sharing our entire app(s)

### LINKED ISSUE #221: Build hangs when watching with 1.3.2
I'm trying to update from version 1.2.0 to 1.3.x. So far I've only updated ember-cli-typescript and typescript to the latest. I'm starting a build with `--watch` and after the build completes I've changed the file `router.ts`. After detecting the changes, nothing happens. I cannot stop the build with ctrl-c, but have to kill the node process using task manager.

```
$ ember build --output ../cb-ember/ --watch
WARNING: Node v10.4.0 is not tested against Ember CLI on your platform. We recommend that you use the most-recent "Active LTS" version of Node.js. See https://git.io/v7S5n for details.

Build successful (110806ms)



Slowest Nodes (totalTime => 5% )              | Total (avg)
----------------------------------------------+---------------------
Babel: ember-test-helpers (2)                 | 20571ms (10285 ms)
Babel: lodash (1)                             | 16651ms
broccoli-persistent-filter:SimpleReplace (3)  | 11898ms (3966 ms)
LessCompiler (1)                              | 9880ms
Babel: ember-data (2)                         | 9038ms (4519 ms)

file added oqt3obpy.4lo~
file deleted oqt3obpy.4lo~
file changed router.ts
```

* Attempt 1, update only typescript and ember-cli-typescript:
   ```
   ember-cli: 3.0.2
   typescript: 2.9.1
   ember-cli-typescript: 1.3.2
   ```

* Attempt 2, update everything (`yarn upgrade`).

What other information do you need to look into this? I can't provide the source code.

### PR DESCRIPTION
**Pull request by dfreeman**
The change in #196 was nice in that it simplified our code, but unfortunately it wasn't a faithful recreation of how tsc's own watcher works. It turns out we're forcing tsc to do extra work by treating every file change as a directory-level action, and we're also running into an inconsistency in how tsc deals with setting up directory watches depending on the name of the folder the project is in.

This should fix #204 and fix #221. It also supersedes #215. I've stress tested it a bit with the `type-generation` branch, and ~I believe between the slightly different implementation here and the change in #218, the problem that #196 was originally addressing is no longer an issue.~ Scratch that. Investigation underway.

I'd love to confirm with at least one of @pixelhandler and/or @bouke that this solves the rebuild issues they were having before merging.

### CODE REVIEW

**Comment by pixelhandler** [comment]
@dfreeman yes this branch fixes the rebuild issue I reported on #204. Just ran this branch with my app and changes to .ts files resulted in successful rebuilds while running `ember b -w`. Thanks for working on this :)

**Comment by Bouke** [comment]
@dfreeman this branch also resolves the issue I reported in #221. I also tested with `ember build --watch` in side my directory containing dots. Thank you for putting in the energy to resolve our issues!

**Comment by Bouke** [comment]
Removing a file gives the following errors, should those be covered by this?

```
file deleted routes\bouke.ts
error TS6053: File 'C:/My.Project.Name/app/routes/bouke.ts' not found.

Build successful (4166ms)



Slowest Nodes (totalTime => 5% )              | Total (avg)
----------------------------------------------+---------------------
Funnel (24)                                   | 743ms (30 ms)
LessCompiler (1)                              | 524ms
broccoli-persistent-filter:SimpleReplace (3)  | 438ms (146 ms)
Funnel: Addon JS (19)                         | 372ms (19 ms)
broccoli-persistent-filter:Babel > [Ba... (1) | 295ms

file changed routes\about.ts
error TS6053: File 'C:/My.Project.Name/app/routes/bouke.ts' not found.

Build successful (2928ms)
```

And after adding the same file again, the build is still hanging.

Adding a new file from a new watched build, gives the following error:
```
Build successful (88718ms)



Slowest Nodes (totalTime => 5% )              | Total (avg)
----------------------------------------------+---------------------
Babel (33)                                    | 36032ms (1091 ms)
LessCompiler (1)                              | 14521ms
SimpleReplace (3)                             | 12561ms (4187 ms)

EPERM: operation not permitted, lstat 'C:\My.Project.Name\app\routes\bouke3.ts'


Stack Trace and Error Report: C:\Users\Bouke\AppData\Local\Temp/error.dump.018cba7791c06d3789a076b620cb9bda.log
Cannot stop: not the current node.
Cannot stop: not the current node.
Cannot stop: not the current node.
Cannot stop: not the current node.
file added routes\bouke3.ts
Cannot stop: not the current node.
Cannot stop: not the current node.
Build Canceled

cannot build this builder, as it has been previously canceled


Stack Trace and Error Report: C:\Users\Bouke\AppData\Local\Temp/error.dump.cbb22e5ad9d3b42c70b59c154401c1a7.log
file added routes\bouke3.ts
cannot build this builder, as it has been previously canceled


Stack Trace and Error Report: C:\Users\Bouke\AppData\Local\Temp/error.dump.3e288bea1831e096ea4ae4f4dd759573.log
```

Also something else I've noticed is that Sublime doesn't show the file additions/deletions when the watched build is running. Could Windows be running into some limit here?

**Comment by dfreeman** [comment]
Alright, an update on this — even with the change I originally made here, tsc's own weirdness with directories that have `.` in them was still biting us. I've updated this so that the default blueprint adds `**/*` to the end of the paths in `include`, which gets tsc to stop thinking `dir.name` is somehow a glob on its own. Between that and a fix for a casing mismatch between tsc and chokidar, this _should_ work nicely across the board now. I've verified locally and in a Windows VM that that seems to be the case.

> Also something else I've noticed is that Sublime doesn't show the file additions/deletions when the watched build is running. Could Windows be running into some limit here?

I couldn't say for certain, but historically (in my own experience at least), Sublime has never been great with filesystem events. I'm not sure if there's a near-term fix, but I'd expect this to improve when Broccoli 2 lands in ember-cli, which will allow the `tmp` directory to move out of the project and into system temp.

**Comment by Bouke** [comment]
I changed my `tsconfig.json` to include `**/*`, and after that it all appears to work great! I did a few changes and file additions / deletions / renames and the build runs every time. There's an occasional error message printed, but it doesn't appear to affect the build itself:

```
Cannot stop: not the current node.
Cannot stop: not the current node.
file changed router.ts
Build Canceled

file changed router.ts
file changed router.ts
cannot build this builder, as it has been previously canceled


Stack Trace and Error Report: C:\Users\Bouke\AppData\Local\Temp/error.dump.701ac305e3eff3f67a29ba374793601e.log

Build successful (7951ms)
```

```
file deleted routes\about.ts
Build Error (EslintValidationFilter)

ENOENT: no such file or directory, stat 'C:\My.Project.Name\tmp\funnel-output_path-O6j5sLVx.tmp\routes\about2.ts'


Stack Trace and Error Report: C:\Users\Bouke\AppData\Local\Temp/error.dump.ee89fefd88ae82250d9b6d67a9568320.log
file deleted routes\about2.ts
file added routes\about.ts

Build successful (6237ms)
```

> I couldn't say for certain, but historically (in my own experience at least), Sublime has never been great with filesystem events. I'm not sure if there's a near-term fix, but I'd expect this to improve when Broccoli 2 lands in ember-cli, which will allow the tmp directory to move out of the project and into system temp.

Ok great. It was just an observation, not sure if it has anything to do with this project. Thanks, I'll keep an eye out for those improvements in ember / brocolli. 👍

**Comment by dfreeman** [comment]
@Bouke In that first trace, had you canceled the build, or do you get those `Cannot stop: not the current node` errors just during active watched builds? For the second, it _looks_ like that error is coming from ESLint, but it's certainly interesting that it's happening when a `.ts` file changes.

In both cases (and just in general), if you're able to either include the contents of the `Stack Trace and Error Report` file it references in the output as part of the issue or DM them to me on Slack, that can provide us a lot more information to go on.

Regardless, I'm glad things seem to be working for you! 🎉

**Comment by Bouke** [comment]
@dfreeman yes both these errors occurred in the same watched build, when adding/removing/deleting some files. Probably the timing of these file operations was just right to trigger those errors. The build did continue and no problems seem to have occurred. We're currently working off this branch, and it all seems to be fine thus far.

**Comment by chriskrycho** [comment]
I'm going to do some local testing and then presumably merge this by the end of the week! Sorry for the delays; I've been *much* occupied by my primary tasks at work.

**Comment by pixelhandler** [comment]
@chriskrycho let me know if you'd like me to test anything here.

**Comment by pixelhandler** [comment]
@chriskrycho I tested out our app, using, `ember s`, `ember b -w`, `ember t -s`, used the generator to create a component, modified existing typescript files, changed .js file to .ts file. Everything worked as expected, rebuilds fired off etc. This is great :+1:

**Pull request merged**
