### PR TITLE
Expose app files via a preprocessor so they take precedence

### PR DESCRIPTION
**Pull request by dfreeman**
Locally, this solves issue number 1 in #126 (addons' `app` files clobbering local ones) for me. @toranb if you have a moment at some point, would you mind giving this branch a spin and confirming?

@chriskrycho I know you said you ran into this as well.

### CODE REVIEW

**Comment by chriskrycho** [comment]
Confirmed fixed locally. I'll wait to merge till we have confirmation from @toranb (probably tomorrow, it's getting late!).

**Comment by toranb** [comment]
Great work @dfreeman !! Thanks for the quick look at this guys - happy to report it's correctly generating the JS output for reducers written with TypeScript :)

**Comment by CvX** [comment]
This commit breaks the build in my application. For whatever reason the compiled TS code is now appended to the `assets/[app-name]-fastboot.js`, along with some metadata that trips up the parser:

```
{"version":3,"file":"round.js","sourceRoot":"","sources":["../../../../app/app/lib/round.ts"],"names":[],"mappings":"AAAA,MAAM,CAAC,OAAO,gBAAgB,KAAa,EAAE,SAAiB;IAC5D,EAAE,CAAC,CAAC,SAAS,KAAK,CAAC,CAAC,CAAC,CAAC;QACpB,MAAM,CAAC,IAAI,CAAC,KAAK,CAAC,KAAK,CAAC,CAAC;IAC3B,CAAC;IAAC,IAAI,CAAC,EAAE,CAAC,CAAC,KAAK,CAAC,KAAK,CAAC,IAAI,SAAS,GAAG,CAAC,KAAK,CAAC,CAAC,CAAC,CAAC;QAC/C,MAAM,CAAC,GAAG,CAAC;IACb,CAAC;IAAC,IAAI,CAAC,EAAE,CAAC,CAAC,KAAK,GAAG,CAAC,CAAC,CAAC,CAAC;QACrB,MAAM,CAAC,CAAC,KAAK,CAAC,CAAC,KAAK,EAAE,SAAS,CAAC,CAAC;IACnC,CAAC;IAED,IAAI,CAAC,OAAO,EAAE,GAAG,CAAC,GAAG,KAAK,CAAC,QAAQ,EAAE,CAAC,KAAK,CAAC,GAAG,CAAC,CAAC;IACjD,KAAK,GAAG,IAAI,CAAC,KAAK,CAAC,CAAC,CAAC,OAAO,GAAG,GAAG,GAAG,CAAC,GAAG,CAAC,CAAC,CAAC,CAAC,CAAC,GAAG,GAAG,SAAS,CAAC,CAAC,CAAC,CAAC,SAAS,CAAC,CAAC,CAAC,CAAC;IAE9E,CAAC,OAAO,EAAE,GAAG,CAAC,GAAG,KAAK,CAAC,QAAQ,EAAE,CAAC,KAAK,CAAC,GAAG,CAAC,CAAC;IAC7C,MAAM,CAAC,CAAC,CAAC,OAAO,GAAG,GAAG,GAAG,CAAC,GAAG,CAAC,CAAC,CAAC,CAAC,CAAC,GAAG,GAAG,SAAS,CAAC,CAAC,CAAC,CAAC,CAAC,SAAS,CAAC,CAAC,CAAC;AACpE,CAAC"}
```

```
App is being served by FastBoot
/app/tmp/broccoli_merge_trees-output_path-CNMloWBG.tmp/assets/frontend-fastboot.js:106
{"version":3,"file":"round.js","sourceRoot":"","sources":["../../../../app/app/lib/round.ts"],"names":[],"mappings":"AAAA…

SyntaxError: Unexpected token :
    at VMSandbox.eval (/app/node_modules/fastboot/src/vm-sandbox.js:13:22)
    at /app/node_modules/fastboot/src/ember-app.js:163:15
    at Array.forEach (<anonymous>)
    at EmberApp.loadAppFiles (/app/node_modules/fastboot/src/ember-app.js:160:18)
    at EmberApp.retrieveSandboxedApp (/app/node_modules/fastboot/src/ember-app.js:201:10)
    at new EmberApp (/app/node_modules/fastboot/src/ember-app.js:59:21)
    at FastBoot._buildEmberApp (/app/node_modules/fastboot/src/index.js:114:17)
    at new FastBoot (/app/node_modules/fastboot/src/index.js:52:10)
    at app.use (/app/node_modules/ember-cli-fastboot/index.js:316:29)
    at Layer.handle [as handle_request] (/app/node_modules/express/lib/router/layer.js:95:5)
```

**Comment by chriskrycho** [comment]
That's a quirky side effect; the metadata is the source map.

What is your setting for source maps in Babel? If it's set, it's just in the `babel` key in your `new EmberApp({ ... })` invocation in `ember-cli-build.js`.

You might try changing `inlineSourceMap: false` and/or `inlineSources: false` in your `tsconfig.json` to confirm that that's the problem.

**Comment by CvX** [comment]
No luck - there isn't any babel configuration, and I've tried setting `inlineSourceMap` and `inlineSources` to false, but it doesn't affect the output.

The issue is that before this commit, the output file contained only the initializers:

```
define('frontend/initializers/ajax', ['exports'], function (exports) { … });
define('frontend/initializers/error-handler', ['exports'], function (exports) { … });
```

And after this commit it also contains a lib function:

```
…
define('frontend/lib/round', ['exports'], function (exports) { … });
```

**Comment by dfreeman** [comment]
If I understand how Fastboot works correctly, `[app-name]-fastboot.js` is supposed to contain a full copy of your app built to run in a node environment, so if `frontend/lib/round` was missing before, that was likely a bug.

Unfortunately I haven't been able to reproduce this locally with ember-cli-typescript's own dummy app, with or without sourcemaps enabled.

@CvX can you provide more details about your setup? Your versions of `ember-cli`, `ember-cli-fastboot`, etc? Are your initializers also written in TypeScript, or are they JS?

**Comment by CvX** [comment]
The `[app-name]-fastboot.js` contains only fastboot-related code: https://github.com/ember-fastboot/ember-cli-fastboot/blob/c83e885fb51c5b01f39e966ee54fb865d5bf41ca/index.js#L159

In this case that's only the two fastboot initializers (both JS):

1. https://github.com/ember-fastboot/ember-cli-fastboot/blob/b4c105c/fastboot/initializers/error-handler.js
2. frontend/initializers/ajax from my app

Here's a quick repro: https://github.com/CvX/typescript-debug-app
* `ember build && cat dist/assets/typescript-debug-app-fastboot.js` - there's a compiled TS code in addition to initializers
* lock ember-cli-typescript version to 1.1.3 and rebuild - there are only initializers

**Comment by dfreeman** [comment]
I see that the extra content is there, but I'm not seeing the parser-breaking metadata you're describing, and the app seems to build and serve without any issues.

Obviously including extra content in that output file is bad, and we should investigate ways to avoid doing that—no objection on that front! 😄  My question is just what this actively breaks—what's not working the way it should because of the additional modules?

**Comment by CvX** [comment]
@dfreeman Welp, I was able to consistently reproduce the issue (also after removing tmp/ and node_modules/), though only in my app, not in this minimal repro-app… until I wasn't. 😅
After a couple of rebuilds the issue disappeared…

If it ever comes up again, I'll try to debug as much as I can and I'll create a new issue. 🙃
(Although it even less likely to happen after this PR to fastboot-transform https://github.com/kratiahuja/fastboot-transform/pull/8 😃)

**Pull request merged**
