### PR TITLE
perf: don't use middleware if has build

### PR DESCRIPTION
**Pull request by mrloop**
~This PR depends on a PR for `ember-cli` being merged first, see https://github.com/ember-cli/ember-cli/pull/9205~ **merged**

`ember serve` and `ember test` has a `path` flag to specify
an existing ember build to use, without rebuilding. `ember-cli-typescript`
will add typechecking middleware regardless of ember using an existing
build, the typechecking middleware is not required. This can slow
down the initial request to express server significantly.

For instance one project spends 49 secs for initial typecheck on first
request.

```sh
$ DEBUG=*:* ember s --path dist
...
– Serving on http://localhost:4200/admin/
...
ember-cli-typescript:typecheck-worker Typecheck complete (0 diagnostics) +49s
...
```

### CODE REVIEW

**Comment by jamescdavis** [comment]
I think this could be a nice perf improvement. I've experienced the same and agree that it doesn't make sense to run the type-checking middleware when you're just using an existing build.

**Comment by rwjblue** [comment]
FWIW, the ember-cli PR should land into the ember-cli@3.19.0-beta cycle today/tomorrow.

**Comment by mrloop** [comment]
Thanks @rwjblue I'll update this PR, add a test and remove the `prettier` update and not use optional chaining, this can be added in another PR.

**Comment by mrloop** [comment]
I've updated the PR ready for review, removing the `prettier` update and optional chaining causing prettier linting to fail. I've added tests to check that type checking worker is running or not running for both `ember serve` and `ember test` depending on the `--path` flag. 

One of the required checks are failing `CI / Test (linux, floating dependencies) (pull_request)`, this looks unrelated to PR and not sure how to fix it.

**Comment by chriskrycho** [comment]
Thank you! One of us will try to get to this in the next couple days!

**Comment by mrloop** [comment]
Rebased on master

**Comment by mrloop** [comment]
@chriskrycho is there anything I can do to help get this over line and merged? Is the testing approach good or is there a better way of doing it?

**Comment by jamescdavis** [comment]
Released in [4.0.0-rc.1](https://github.com/typed-ember/ember-cli-typescript/releases/tag/v4.0.0-rc.1)

**Pull request merged**
