### PR TITLE
Add `util` and `util-test`

### PR DESCRIPTION
**Pull request by tansongyang**
There are a couple of things different about this one.

1. I figured that it would reduce noise and clutter to start grouping similar generators together. So, I included both `util` and `util-test`. The generator for `util` was straightforward, just like the others. However ...
2. I got the error `Cannot find module '../test-framework-generator'` in `util-test-test.js`. I'm assuming this is because, in a real Ember app, the CLI is looking at what test framework you have installed and selecting the test file that way. I was hoping there would be another command line argument to specify test framework, but it doesn't look like there is. Any ideas on how to test? For the time being, I just left out tests for `util-test`.

### CODE REVIEW

**Comment by chriskrycho** [comment]
I *think* that’s actually a file we just need to bring over for the sake of making this work, but will confirm in the morning!

**Comment by chriskrycho** [comment]
Never mind about the morning, apparently: [this](https://github.com/emberjs/ember.js/blob/master/blueprints/test-framework-detector.js) is the file we’ll need to bring over to make this work, @tansongyang. It should just go at the same place in *this* library as it does in Ember itself: the root of the blueprints directory.

**Comment by tansongyang** [comment]
@chriskrycho Just glancing at the code, it looks like there's no way to test all styles (`qunit-rfc-232`, `qunit`, _and_ `mocha`). The code just checks your dependencies and chooses one for you, with no option to override. Are we OK with that?

**Comment by chriskrycho** [comment]
We might actually just pull over the blueprint *tests* for these ones as well. (And maybe others! 🤔)

- [utils-test.js](https://github.com/emberjs/ember.js/blob/master/node-tests/blueprints/util-test.js)
- [utils-test-test.js](https://github.com/emberjs/ember.js/blob/master/node-tests/blueprints/util-test-test.js) (that name!)

**Comment by tansongyang** [comment]
I think I got all the important files. `util-test` tests should work.

A couple of things I think are worth discussing:

1. Should I maybe make a different branch for adding the test framework code? This PR has a lot of stuff in it that might make more sense separated.
2. I wasn't aware that there were already blueprint tests in the `ember.js` repo. If I get to any other ones this weekend, I'll probably just be copying tests from there, especially for all the `*-test` generators.

**Comment by chriskrycho** [comment]
1. Nah, I’m not really worried about it in this case.
2. Concur, this was going to be my broad suggestion. I didn’t think of it previously either.

**Pull request merged**
