### PR TITLE
Work out of the box

### LINKED ISSUE #131: Including ember-data typings conflicts with alternative stores
`ember-data` typings might conflict with alternative stores (e.g. orbit), which can provide their own store service. Perhaps there could be a check if parent application depends on ember-data before adding them?

### LINKED ISSUE #136: Work out of the box
Running `ember new` followed by `ember install ember-cli-typescript` should work without any compiler errors.

`@types/ember-qunit` is missing, which causes a compiler error when you try to write a test -- #135.

`@types/ember-data` is included but you still get compiler errors since no registry is defined. We should add the [catch-all registry snippet](https://github.com/typed-ember/ember-cli-typescript#fixing-the-ember-data-error-ts2344-problem) to the blueprint.

For reference, these are the dependencies added by ember-cli 3.0 to a fresh `ember new`:
- broccoli-asset-rev
- ember-ajax
- ember-cli
- ember-cli-app-version
- ember-cli-babel
- ember-cli-dependency-checker
- ember-cli-eslint
- ember-cli-htmlbars
- ember-cli-htmlbars-inline-precompile
- ember-cli-inject-live-reload
- ember-cli-qunit
- ember-cli-shims
- ember-cli-sri
- ember-cli-uglify
- ember-data
- ember-export-application-global
- ember-load-initializers
- ember-maybe-import-regenerator
- ember-resolver
- ember-source
- ember-welcome-page
- eslint-plugin-ember
- loader.js

And for `ember addon`:
- broccoli-asset-rev
- ember-ajax
- ember-cli
- ember-cli-dependency-checker
- ember-cli-eslint
- ember-cli-htmlbars
- ember-cli-htmlbars-inline-precompile
- ember-cli-inject-live-reload
- ember-cli-qunit
- ember-cli-shims
- ember-cli-sri
- ember-cli-uglify
- ember-disable-prototype-extensions
- ember-export-application-global
- ember-load-initializers
- ember-maybe-import-regenerator
- ember-resolver
- ember-source
- ember-source-channel-url
- ember-try
- eslint-plugin-ember
- eslint-plugin-node
- loader.js

### PR DESCRIPTION
**Pull request by jamescdavis**
resolve #136
resolve #131

### CODE REVIEW

**Comment by jamescdavis** [comment]
Sure! I was thinking there should probably be some tests for which types get installed. I'll also add a test for @types/ember-data.

**Comment by jamescdavis** [comment]
The `addon with Mocha` test *might* be redundant, but I guess it doesn't hurt to make sure.

**Comment by jamescdavis** [comment]
Just to be sure, since the ember-data and qunit `@types/` tests rely on ember-cli defaults.

**Comment by jamescdavis** [comment]
I don't really like that these take so long (due to enabling the `npm-install` task), but I don't know of any other way to get `addPackagesToProject` to actually do something testable.
```
  Acceptance: ember-cli-typescript generator
    ✓ basic app (5619ms)
    ✓ basic addon (4876ms)
    ✓ in-repo addons (3450ms)
    ✓ app with Mirage (3596ms)
    ✓ addon with Mirage (3333ms)
    ✓ app with Mocha (3311ms)
    ✓ addon with Mocha (4439ms)
```

**Comment by chriskrycho** [comment]
Unfortunately, I think that's just the price to pay here. It stinks, but it's better than shipping something broken. (Note that I'll let @dfreeman or @dwickern review and merge and make any other calls on this – need to be away for the rest of the week.)

**Comment by dfreeman** [comment]
It looks like we're getting timeouts on a few of the tests — can we up the limit in Mocha for those tests to handle when Travis is having a slow day?

**Comment by jamescdavis** [comment]
I took a different approach.

**Pull request merged**
